<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cancellation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cancellation_model');
    } 

    /*
     * Listing of cancellation
     */
    function index()
    {
        $data['cancellation'] = $this->Cancellation_model->get_all_cancellation();
        
        $data['_view'] = 'cancellation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cancellation
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id' => $this->input->post('id'),
				'reservation_id' => $this->input->post('reservation_id'),
				'hotel_id' => $this->input->post('hotel_id'),
				'category_id' => $this->input->post('category_id'),
				'total_price' => $this->input->post('total_price'),
				'cancellation_charge' => $this->input->post('cancellation_charge'),
				'refund_amount' => $this->input->post('refund_amount'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
				'cancel_date' => $this->input->post('cancel_date'),
            );
            
            $cancellation_id = $this->Cancellation_model->add_cancellation($params);
            redirect('cancellation/index');
        }
        else
        {            
            $data['_view'] = 'cancellation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cancellation
     */
    function edit($id)
    {   
        // check if the cancellation exists before trying to edit it
        $data['cancellation'] = $this->Cancellation_model->get_cancellation($id);
        
        if(isset($data['cancellation']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id' => $this->input->post('id'),
					'reservation_id' => $this->input->post('reservation_id'),
					'hotel_id' => $this->input->post('hotel_id'),
					'category_id' => $this->input->post('category_id'),
					'total_price' => $this->input->post('total_price'),
					'cancellation_charge' => $this->input->post('cancellation_charge'),
					'refund_amount' => $this->input->post('refund_amount'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'cancel_date' => $this->input->post('cancel_date'),
                );

                $this->Cancellation_model->update_cancellation($id,$params);            
                redirect('cancellation/index');
            }
            else
            {
                $data['_view'] = 'cancellation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cancellation you are trying to edit does not exist.');
    } 

    /*
     * Deleting cancellation
     */
    function remove($id)
    {
        $cancellation = $this->Cancellation_model->get_cancellation($id);

        // check if the cancellation exists before trying to delete it
        if(isset($cancellation['']))
        {
            $this->Cancellation_model->delete_cancellation($id);
            redirect('cancellation/index');
        }
        else
            show_error('The cancellation you are trying to delete does not exist.');
    }
    

    function cancelbooking($id)
    {   

        $booking = $this->Reservation_model->get_reservation($id);

        $bookingparams = array('booking_status'=>'cancelled');
        $this->Reservation_model->update_reservation($id,$bookingparams);            
        
        
          
            $params = array(
			
				'reservation_id' => $booking['id'],
				'hotel_id' => $booking['hotel_id'],
				'category_id' => $booking['category_id'],
				'total_price' => $booking['total_price'],
				// 'cancellation_charge' => $this->input->post('cancellation_charge'),
				// 'refund_amount' => $this->input->post('refund_amount'),
				
				'cancel_date' => date('Y-M-D'),
            );
            
            $cancellation_id = $this->Cancellation_model->add_cancellation($params);
            echo $cancellation_id;
            
            // redirect('cancellation/index');
        // }
        // else
        // {            
        //     $data['_view'] = 'cancellation/add';
        //     $this->load->view('layouts/main',$data);
        // }
    } 
}
