<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Careers extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library('session');

    } 

    /*
     * Listing of amenities
     */
    public function index()
    {
        if(isset($_POST) && count($_POST) > 0)     
        {   
                   
            $params = array(
            'fname' => $this->input->post('firstname'),
            'lname' => $this->input->post('lastname'),
            'c_number' => $this->input->post('contact_number'),
            'emailId' => $this->input->post('emailId'),
            'c_optn' => $this->input->post('career_optn'),
            'p_summary' => $this->input->post('profile_summary'),
            );
            $this->session->set_userdata($params);
            redirect('Send_email/index/');
            
        }
        else{
            $this->load->view('frontend/c_form');
            }
        
    }



}

