<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Margin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Margin_model');
        $this->load->model('Hotel_model');
    } 

    /*
     * Listing of amenities
     */
    function index()
    {
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
      if($this->session->userdata('user_type')== 1){
                    $id= $this->session->userdata('login_id');
                    $data['margins'] = $this->Margin_model->get_all_margins();
                } 
       
        elseif($this->session->userdata('user_type')==2){
                    $id= $this->session->userdata('login_id');
                    $data['margins'] = $this->Margin_model->get_all_margins_by_id($id);
                }
        
        $data['_view'] = 'margin/index';
        $this->load->view('admin/index',$data);
    }

    /*
     * Adding a new amenity
     */
    function add()
    {   
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1){
          $data['hotels'] = $this->Hotel_model->get_all_hotels(); 
        if(isset($_POST) && count($_POST) > 0)     
        {   
           
            $params = array(
				'hotel_id' => $this->input->post('name'),
                'percentage'=>$this->input->post('percentage')
				
            );
            
            $margin_id = $this->Margin_model->add_margin($params);
            redirect('margin/index');
        }
        else
        {            
            $data['_view'] = 'margin/add';
            $this->load->view('admin/index',$data);
        }
    }else{
        show_error('you are not permitted to access this page');
    }
    }  

    /*
     * Editing a amenity
     */
    function edit($id)
    {   
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1){
        // check if the amenity exists before trying to edit it
        $data['margin'] = $this->Margin_model->get_margin($id);
           $data['hotels'] = $this->Hotel_model->get_all_hotels(); 
        
        if(isset($data['margin']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {  
            $date=date('Y-m-d H:i:s'); 

                $params = array(
					'hotel_id' => $this->input->post('name'),
				
					'percentage' =>$this->input->post('percentage'),
                );
                // print_r($params);
                // die;

                $this->Margin_model->update_margin($id,$params);            
                redirect('margin/index');
            }
            else
            {
                $data['_view'] = 'margin/edit';
                $this->load->view('admin/index',$data);
            }
        }
        else
            show_error('The Hotel Payment Margin  you are trying to edit does not exist.');
    }else{
        show_error('you are not permitted to access this page');
    }
    } 

    /*
     * Deleting amenity
     */
    function remove($id)
    {

        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1){
        $margin= $this->Margin_model->get_margin($id);

        // check if the amenity exists before trying to delete it
        if(isset($margin['id']))
        {
            $this->Margin_model->delete_margin($id);
            redirect('margin/index');
        }
        else
            show_error('The Hotel Payment Margin you are trying to delete does not exist.');
        }else{
            show_error('you are not permitted to access this page');
        }
    }
    
}
