<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Room_category_model');
        $this->load->model('Hotel_model'); 
        $this->load->model('Amenity_model');
    } 

    /*
     * Listing of room_categories
     */
    function index()
    {
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
       
         
        if($this->session->userdata('user_type')==1){
             $data['room_categories'] = $this->Room_category_model->get_all_room_categories();
            $data['hotels'] = $this->Hotel_model->get_all_hotels();
          
                }
                elseif($this->session->userdata('user_type')==2){
                   $id= $this->session->userdata('login_id');
                    $data['hotels'] = $this->Hotel_model->get_all_hotels($id);
                     $data['room_categories'] = $this->Room_category_model->get_all_room_categories($id);
                }
             //$data['hotels'] = $this->Hotel_model->get_all_hotels();
              $data['amenities'] = $this->Amenity_model->get_all_amenities();
        $data['_view'] = 'room_category/index';
        $this->load->view('admin/index',$data);
    }


    function viewsub()
    {
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        
         // var_dump($data['room_categories']);die;
        if($this->session->userdata('user_type')==1){
            $data['hotels'] = $this->Hotel_model->get_all_hotels();
            $data['room_categories'] = $this->Room_category_model->get_all_room_sub_categories();
          
                }
                elseif($this->session->userdata('user_type')==2){
                    $id= $this->session->userdata('login_id');
                    $data['hotels'] = $this->Hotel_model->get_all_hotels($id);
                    $data['room_categories'] = $this->Room_category_model->get_all_room_sub_categories($id);
                    // print_r($data['room_categories']);
                    // die();
                }
            //  $data['hotels'] = $this->Hotel_model->get_all_hotels();
              $data['amenities'] = $this->Amenity_model->get_all_amenities();
        $data['_view'] = 'subrooms/index';
        $this->load->view('admin/index',$data);
    }

    /*
     * Adding a new room_category
     */
    function add()
    { 
       
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
        if($this->session->userdata('user_type')==1){
            $data['hotels'] = $this->Hotel_model->get_all_hotels();
          
                }
                elseif($this->session->userdata('user_type')==2){
                    $id= $this->session->userdata('login_id');
                    $data['hotels'] = $this->Hotel_model->get_all_hotels($id);
                }

               
            
              $data['amenities'] = $this->Amenity_model->get_all_amenities();
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $hotel_id = $this->input->post('hotel_id');
            $params = array(
				'hotel_id' => $this->input->post('hotel_id'),
				'category_name' => $this->input->post('category_name'),
				'no_of_rooms' => $this->input->post('no_of_rooms'),
				'capacity' => $this->input->post('capacity'),
                'baseprice' => $this->input->post('baseprice'),
				'price' => $this->input->post('price'),
				'amenities' =>implode(',', $this->input->post('amenities')),
				'created_at' => $this->input->post('created_at'),
				
				'description' => $this->input->post('description'),
                'cancellation_policy'=>$this->input->post('cancellation_policy'),
                'double_price'=>$this->input->post('doubleprice'),
                'extra_bed_price'=>$this->input->post('bedprice'),
                'refund_status'=>$this->input->post('refund')
            );
            $room_category_id = $this->Room_category_model->add_room_category($params);
            
            // add a sub category with same name, this is for inventory which is maintained
            // for each sub category, it will ensure each category has atleast one subcategory
            // type.
            
            $params = array(
                'hotel_id' => $this->input->post('hotel_id'),
                'category_id' => $room_category_id,
                'sub_name' => $this->input->post('category_name'),
                'num_of_rooms' => $this->input->post('no_of_rooms'),
                'capacity' => $this->input->post('capacity'),
                'base_price' => $this->input->post('baseprice'),
                'price' => $this->input->post('price'),
                'amenities' =>implode(',', $this->input->post('amenities')),
                'created_at' => $this->input->post('created_at'),
                 'cancellation_policy'=>$this->input->post('cancellation_policy'),
                 'double_price'=>$this->input->post('doubleprice'),
                'extra_bed_price'=>$this->input->post('bedprice')
                
            );
            $sub_id = $this->Room_category_model->add_sub_rooms($params);
            // print_r($sub_id);
             
             if(count($_FILES['hotel_gallery']['name'])>0 && $_FILES['hotel_gallery']['name'][0] != ''){
			 $filesCount = count($_FILES['hotel_gallery']['name']);

             $files=implode(",", $_FILES['hotel_gallery']['name']);
            for($i = 0; $i < $filesCount; $i++){
                $_FILES['file']['name']     = $_FILES['hotel_gallery']['name'][$i];
                $_FILES['file']['type']     = $_FILES['hotel_gallery']['type'][$i];
                $_FILES['file']['tmp_name'] = $_FILES['hotel_gallery']['tmp_name'][$i];
                $_FILES['file']['error']     = $_FILES['hotel_gallery']['error'][$i];
                $_FILES['file']['size']     = $_FILES['hotel_gallery']['size'][$i];
                
                // File upload configuration
                $uploadPath = 'gallery/'.$hotel_id.'/roompics'.'/'.$room_category_id;
                // $uploadPath = 'roompics/';
                if(!is_dir($uploadPath)){
                    mkdir($uploadPath,0777,true);
                }
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                
                // Load and initialize upload library
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                
                // Upload file to server
                $this->upload->do_upload('file');
                $uploadPath = 'gallery/'.$hotel_id.'/subroompics'.'/'.$sub_id;
                  if(!is_dir($uploadPath)){
                    mkdir($uploadPath,0777,true);
                }
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                
                // Load and initialize upload library
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                
                // Upload file to server
                $this->upload->do_upload('file');
            }
            
			
            $gallery=array(
                            "hotel_id"=>$this->input->post('hotel_id'),
                            "category_id"=> $room_category_id,
                            "gallery"=>$files);
            $this->Hotel_model->add_gallery($gallery);
            $gallery1=array(
                "hotel_id"=>$this->input->post('hotel_id'),
                "category_id"=>$room_category_id,
                "sub_category_id"=>$sub_id, 
                "gallery"=>$files);
$this->Hotel_model->add_sub_gallery($gallery1);
            
             }            
           
            redirect('room_category/index');
        }
        else
        {            
            $data['_view'] = 'room_category/add';
            $this->load->view('admin/index',$data);
        }
    }else{
        show_error('you are not permitted to access this page');
    }
    }  

    /*
     * Editing a room_category
     */
    function edit($id)
    {   

        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
        // check if the room_category exists before trying to edit it
        $data['room_category'] = $this->Room_category_model->get_room_category($id);

          if($this->session->userdata('user_type')==1){
            $data['hotels'] = $this->Hotel_model->get_all_hotels();
          
                }
                elseif($this->session->userdata('user_type')==2){
                    $id= $this->session->userdata('login_id');
                    $data['hotels'] = $this->Hotel_model->get_all_hotels($id);
                }
        $this->load->model('Amenity_model'); 
            //  $data['hotels'] = $this->Hotel_model->get_all_hotels();
                // $data['hotel'] = $this->Room_category_model->get_hotel($id);
              $data['amenities'] = $this->Amenity_model->get_all_amenities();
              $data['sub_categories']=$this->Room_category_model->get_subcategories_by_category($id);

        if(isset($data['room_category']['id']))
        {
            $date=date('Y-m-d H:i:s');
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $hotel_id = $this->input->post('hotel_id');
                $params = array(
					'hotel_id' => $this->input->post('hotel_id'),
					'category_name' => $this->input->post('category_name'),
					'no_of_rooms' => $this->input->post('no_of_rooms'),
					'capacity' => $this->input->post('capacity'),
                    'baseprice' => $this->input->post('baseprice'),
					'price' => $this->input->post('price'),
					'amenities' => implode(',',$this->input->post('amenities')),
					 'cancellation_policy'=>$this->input->post('cancellation_policy'),
					'updated_at' => $date,
					'description' => $this->input->post('description'),
                     'double_price'=>$this->input->post('doubleprice'),
                'extra_bed_price'=>$this->input->post('bedprice'),
                'refund_status'=>$this->input->post('refund')
                );
                $this->Room_category_model->update_room_category($id,$params); 
 // foreach($data['sub_categories'] as $sub)
 //              {
 //                if($data['room_category']['category_name']==$sub['sub_name'])
 //                {

 //                 $params = array(
 //                'hotel_id' => $this->input->post('hotel_id'),
 //                'category_id' => $room_category_id,
 //                'sub_name' => $this->input->post('category_name'),
 //                'num_of_rooms' => $this->input->post('no_of_rooms'),
 //                'capacity' => $this->input->post('capacity'),
 //                'base_price' => $this->input->post('baseprice'),
 //                'price' => $this->input->post('price'),
 //                'amenities' =>implode(',', $this->input->post('amenities')),
 //                'created_at' => $this->input->post('created_at'),
 //            );
 //            $sub_id = $this->Room_category_model->update_sub_category($id,$params);
                    
 //                }
 //              }
                 $params = array(
                'hotel_id' => $this->input->post('hotel_id'),
                'category_id' => $id,
                'sub_name' => $this->input->post('category_name'),
                'num_of_rooms' => $this->input->post('no_of_rooms'),
                'capacity' => $this->input->post('capacity'),
                'base_price' => $this->input->post('baseprice'),
                'price' => $this->input->post('price'),
                'amenities' =>implode(',', $this->input->post('amenities')),
                 'cancellation_policy'=>$this->input->post('cancellation_policy'),
                  'double_price'=>$this->input->post('doubleprice'),
                'extra_bed_price'=>$this->input->post('bedprice')
                // 'updated_at' => $date,
                //     'description' => $this->input->post('description'),
                );
                 $min=$this->Room_category_model->update_sub_room($hotel_id,$id);
                 // print_r($min['min']);
                 // print_r($min);
                 // die;
                 $this->Room_category_model->update_category_sub_category($min['min'],$params);
             if(count($_FILES['hotel_gallery']['name'])>0 && $_FILES['hotel_gallery']['name'][0] != ''){

			 $filesCount = count($_FILES['hotel_gallery']['name']);

             $files=implode(",", $_FILES['hotel_gallery']['name']);
            for($i = 0; $i < $filesCount; $i++){
                $_FILES['file']['name']     = $_FILES['hotel_gallery']['name'][$i];
                $_FILES['file']['type']     = $_FILES['hotel_gallery']['type'][$i];
                $_FILES['file']['tmp_name'] = $_FILES['hotel_gallery']['tmp_name'][$i];
                $_FILES['file']['error']     = $_FILES['hotel_gallery']['error'][$i];
                $_FILES['file']['size']     = $_FILES['hotel_gallery']['size'][$i];
                
                // File upload configuration
                // $uploadPath = 'roompics/';
                $uploadPath = 'gallery/'.$hotel_id.'/roompics'.'/'.$id;
                // echo $uploadPath;die;
                if(!is_dir($uploadPath)){
                    mkdir($uploadPath,0777,true);
                }
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                
                // Load and initialize upload library
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                
                // Upload file to server
                $this->upload->do_upload('file');
                 $uploadPath = 'gallery/'.$hotel_id.'/subroompics'.'/'.$min['id'];
                  if(!is_dir($uploadPath)){
                    mkdir($uploadPath,0777,true);
                }
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                
                // Load and initialize upload library
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                
                // Upload file to server
                $this->upload->do_upload('file');
            }
        
			
			 $gallery=array(
                            "hotel_id"=>$this->input->post('hotel_id'),
                            'category_id'=> $id,
							"gallery"=>$files);
            $this->Hotel_model->update_room_gallery($gallery);	
            $gallery1=array(
                            "hotel_id"=>$this->input->post('hotel_id'),
                            'sub_category_id'=> $min['id'],
                            "gallery"=>$files);
            $this->Hotel_model->update_sub_gallery($gallery1);  	
             }		
                redirect('room_category/index');
            }
            else
            {
               
                // $data['gallery']=
                $data['room_images'] = $this->Room_category_model->get_pics($data['room_category']['hotel_id'],$id);
                echo $this->db->last_query();
                // var_dump($data);die;
                $data['_view'] = 'room_category/edit';
                $this->load->view('admin/index',$data);
            }
        }
        else
            show_error('The room_category you are trying to edit does not exist.');
        }else{
            show_error('you are not permitted to access this page');
        }
    } 

    // function subedit($id)
    // {   

    //     if (!$this->session->userdata('is_logged_in')) {
    //         redirect('login_user/login');
    //     } 
    //     if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
    //     // check if the room_category exists before trying to edit it
    //     $data['sub_category'] = $this->Room_category_model->get_sub_room_category($id);

    //       if($this->session->userdata('user_type')==1){
    //         $data['hotels'] = $this->Hotel_model->get_all_hotels();
          
    //             }
    //             elseif($this->session->userdata('user_type')==2){
    //                 $id= $this->session->userdata('login_id');
    //                 $data['hotels'] = $this->Hotel_model->get_all_hotels($id);
    //             }
    //     $this->load->model('Amenity_model'); 
    //         //  $data['hotels'] = $this->Hotel_model->get_all_hotels();
    //             // $data['hotel'] = $this->Room_category_model->get_hotel($id);
    //           $data['amenities'] = $this->Amenity_model->get_all_amenities();
    //     if(isset($data['sub_category']['id']))
    //     {
    //         $date=date('Y-m-d H:i:s');
    //         if(isset($_POST) && count($_POST) > 0)     
    //         {   
    //             $hotel_id = $this->input->post('hotel_id');
    //             $params = array(
				// 	'hotel_id' => $this->input->post('hotel_id'),
    //                 'category_id' => $this->input->post('category_id'),
    //                 'sub_name' => $this->input->post('sub_name'),
				// 	'num_of_rooms' => $this->input->post('no_of_rooms'),
				// 	'capacity' => $this->input->post('capacity'),
    //                 'base_price' => $this->input->post('base_price'),
				// 	'price' => $this->input->post('price'),
				// 	'amenities' => implode(',',$this->input->post('amenities')),
					
				// 	// 'updated_at' => $date,
				// 	// 'description' => $this->input->post('description'),
    //             );
    //             // var_dump($params);die;
    //             $this->Room_category_model->update_sub_category($id,$params); 		
    //           redirect('room_category/viewsub');
    //         //   redirect('room_category/index');
    //         }
    //         else
    //         {
    //             // var_dump($data);die;
    //             $data['_view'] = 'subrooms/edit';
    //             $this->load->view('admin/index',$data);
    //         }
    //     }
    //     else
    //         show_error('The room_category you are trying to edit does not exist.');
    //     }else{
    //         show_error('you are not permitted to access this page');
    //     }
    // } 
 function subedit($id)
    {   

        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
        // check if the room_category exists before trying to edit it
        $data['sub_category'] = $this->Room_category_model->get_sub_room_category($id);
        $data['image']=$this->Hotel_model->get_sub_pic($data['sub_category']['hotel_id'],$data['sub_category']['category_id'],$data['sub_category']['id']);

          if($this->session->userdata('user_type')==1){
            $data['hotels'] = $this->Hotel_model->get_all_hotels();
          
                }
                elseif($this->session->userdata('user_type')==2){
                    $id= $this->session->userdata('login_id');
                    $data['hotels'] = $this->Hotel_model->get_all_hotels($id);
                }
        $this->load->model('Amenity_model'); 
            //  $data['hotels'] = $this->Hotel_model->get_all_hotels();
                // $data['hotel'] = $this->Room_category_model->get_hotel($id);
              $data['amenities'] = $this->Amenity_model->get_all_amenities();
        if(isset($data['sub_category']['id']))
        {
            $date=date('Y-m-d H:i:s');
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $hotel_id = $this->input->post('hotel_id');
                $params = array(
                    'hotel_id' => $this->input->post('hotel_id'),
                    'category_id' => $this->input->post('category_id'),
                    'sub_name' => $this->input->post('sub_name'),
                    'num_of_rooms' => $this->input->post('no_of_rooms'),
                    'capacity' => $this->input->post('capacity'),
                    'base_price' => $this->input->post('base_price'),
                    'price' => $this->input->post('price'),
                    'amenities' => implode(',',$this->input->post('amenities')),
                    'double_price'=>$this->input->post('doubleprice'),
                    'extra_bed_price'=>$this->input->post('bedprice'),
                     'cancellation_policy' => $this->input->post('cancellation_policy')
                    
                    // 'updated_at' => $date,
                    // 'description' => $this->input->post('description'),
                );
                 if(count($_FILES['hotel_gallery']['name'])>0 && $_FILES['hotel_gallery']['name'][0] != ''){

             $filesCount = count($_FILES['hotel_gallery']['name']);

             $files=implode(",", $_FILES['hotel_gallery']['name']);
            for($i = 0; $i < $filesCount; $i++){
                $_FILES['file']['name']     = $_FILES['hotel_gallery']['name'][$i];
                $_FILES['file']['type']     = $_FILES['hotel_gallery']['type'][$i];
                $_FILES['file']['tmp_name'] = $_FILES['hotel_gallery']['tmp_name'][$i];
                $_FILES['file']['error']     = $_FILES['hotel_gallery']['error'][$i];
                $_FILES['file']['size']     = $_FILES['hotel_gallery']['size'][$i];
                
                // File upload configuration
                // $uploadPath = 'roompics/';
                // $uploadPath = 'gallery/'.$hotel_id.'/roompics'.'/'.$id;
                $uploadPath = 'gallery/'.$hotel_id.'/subroompics'.'/'.$id;
                // echo $uploadPath;die;
                if(!is_dir($uploadPath)){
                    mkdir($uploadPath,0777,true);
                }
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                
                // Load and initialize upload library
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                
                // Upload file to server
                $this->upload->do_upload('file');
            }
        
            
             $gallery=array(
                            "hotel_id"=>$this->input->post('hotel_id'),
                            'sub_category_id'=> $id,
                            "gallery"=>$files);
            $this->Hotel_model->update_sub_gallery($gallery);      
             }      
                
                // var_dump($params);die;
                $this->Room_category_model->update_sub_category($id,$params);       
              redirect('room_category/viewsub');
            //   redirect('room_category/index');
            }
            else
            {
                // var_dump($data);die;
                $data['_view'] = 'subrooms/edit';
                $this->load->view('admin/index',$data);
            }
        }
        else
            show_error('The room_category you are trying to edit does not exist.');
        }else{
            show_error('you are not permitted to access this page');
        }
    } 

    /*
     * Deleting room_category
     */
    function remove($id)
    {
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
        $room_category = $this->Room_category_model->get_room_category($id);

        // check if the room_category exists before trying to delete it
        if(isset($room_category['id']))
        {
            $this->Room_category_model->delete_room_category($id);
            redirect('room_category/index');
        }
        else
            show_error('The room_category you are trying to delete does not exist.');
        }else{
            show_error('you are not permitted to access this page');
        }
    }

    function subremove($id)
    {
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
        $sub_category = $this->Room_category_model->get_room_category($id);

        // check if the room_category exists before trying to delete it
        if(isset($sub_category['id']))
        {
            $this->Room_category_model->delete_sub_category($id);
            // redirect('room_category/index');
            redirect('room_category/viewsub');

        }
        else
            show_error('The room_category you are trying to delete does not exist.');
        }else{
            show_error('you are not permitted to access this page');
        }
    }

 public function myformAjax($id) { 

       $result = $this->Room_category_model->get_all_room_categories_by_htl($id);;

       echo json_encode($result);

   }

    function addsub()
    { 
       
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
        if($this->session->userdata('user_type')==1){
            $data['hotels'] = $this->Hotel_model->get_all_hotels();
          
                }
                elseif($this->session->userdata('user_type')==2){
                    $id= $this->session->userdata('login_id');
                    $data['hotels'] = $this->Hotel_model->get_all_hotels($id);
                }
         // $data['category'] = $this->Room_category_model->get_all_room_categories();
        
            // var_dump($data['category']);die;
        
            //  $data['hotels'] = $this->Hotel_model->get_all_hotels();
              $data['amenities'] = $this->Amenity_model->get_all_amenities();
        if(isset($_POST) && count($_POST) > 0)     
        {   
              $hotel_id = $this->input->post('hotel_id');
            $params = array(
                'hotel_id' => $this->input->post('hotel_id'),
                'category_id' => $this->input->post('category_id'),
                'sub_name' => $this->input->post('sub_name'),
                'num_of_rooms' => $this->input->post('no_of_rooms'),
                'capacity' => $this->input->post('capacity'),
                'base_price' => $this->input->post('base_price'),
                'price' => $this->input->post('price'),
                'amenities' =>implode(',', $this->input->post('amenities')),
                'created_at' => $this->input->post('created_at'),
                 'cancellation_policy'=>$this->input->post('cancellation_policy'),
                 'double_price'=>$this->input->post('doubleprice'),
                'extra_bed_price'=>$this->input->post('bedprice')
                
            );
             $sub_id = $this->Room_category_model->add_sub_rooms($params);
             $filesCount = count($_FILES['hotel_gallery']['name']);

             $files=implode(",", $_FILES['hotel_gallery']['name']);
            for($i = 0; $i < $filesCount; $i++){
                $_FILES['file']['name']     = $_FILES['hotel_gallery']['name'][$i];
                $_FILES['file']['type']     = $_FILES['hotel_gallery']['type'][$i];
                $_FILES['file']['tmp_name'] = $_FILES['hotel_gallery']['tmp_name'][$i];
                $_FILES['file']['error']     = $_FILES['hotel_gallery']['error'][$i];
                $_FILES['file']['size']     = $_FILES['hotel_gallery']['size'][$i];
                
                // File upload configuration
                // $uploadPath = 'gallery/';
                 $uploadPath = 'gallery/'.$hotel_id.'/subroompics'.'/'.$sub_id;
                   if(!is_dir($uploadPath)){
                    mkdir($uploadPath,0777,true);
                }
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                
                // Load and initialize upload library
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                
                // Upload file to server
                $this->upload->do_upload('file');
            }
            
 $gallery=array(
                "hotel_id"=>$this->input->post('hotel_id'),
                "category_id"=>$this->input->post('category_id'),
                "sub_category_id"=>$sub_id, 
                "gallery"=>$files);
$this->Hotel_model->add_sub_gallery($gallery);
            
           
            // redirect('subrooms/add');
              redirect('room_category/viewsub');
        }
        else
        {            
            $data['_view'] = 'subrooms/add';
            $this->load->view('admin/index',$data);
        }
    }else{
        show_error('you are not permitted to access this page');
    }
    }  
    
}
