<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Taxes extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Taxes_model'); 
    } 

    /*
     * Listing of tax
     */
    function index()
    {
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
       
         
        if($this->session->userdata('user_type')==1){
             $data['taxes'] = $this->Taxes_model->get_all_taxes();          
                }
        $data['_view'] = 'taxes/index';
        $this->load->view('admin/index',$data);
    }

    /*
     * Adding a new tax
     */
    function add()
    { 
       
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1){
        if(isset($_POST) && count($_POST) > 0)     
        {               
            $params = array(
                'min' => $this->input->post('min'),
                'max' => $this->input->post('max'),
                'tax' => $this->input->post('tax'),
            );
            $this->Taxes_model->add_tax($params);
            redirect('taxes/index');
        }
        else
        {            
            $data['_view'] = 'taxes/add';
            $this->load->view('admin/index',$data);
        }
    }else{
        show_error('you are not permitted to access this page');
    }
    }  

    /*
     * Editing a tax
     */
    function edit($id)
    {   

        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1){
        $data['taxes'] = $this->Taxes_model->get_taxes($id);

        if(isset($data['taxes']['id']))
        {
            $date=date('Y-m-d H:i:s');
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'min' => $this->input->post('min'),
					'max' => $this->input->post('max'),
					'tax' => $this->input->post('tax'),
                );
                $this->Taxes_model->update_taxes($id,$params); 
 	
                redirect('taxes/index');
            }
            else
            {
                // echo $this->db->last_query();
                $data['_view'] = 'taxes/edit';
                $this->load->view('admin/index',$data);
            }
        }
        else
            show_error('The tax you are trying to edit does not exist.');
        }else{
            show_error('you are not permitted to access this page');
        }
    } 

    /*
     * Deleting tax
     */
    function remove($id)
    {
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 
        if($this->session->userdata('user_type')==1){
        $tax = $this->Taxes_model->get_taxes($id);

        // check if the tax exists before trying to delete it
        if(isset($tax['id']))
        {
            $this->Taxes_model->delete_tax($id);
            redirect('taxes/index');
        }
        else
            show_error('The tax you are trying to delete does not exist.');
        }else{
            show_error('you are not permitted to access this page');
        }
    }

   

 
}
