<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Travel_agent extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vendor_detail_model');
        $this->load->model('Login_user_model');        
        $this->load->model('User_detail_model');        
        $this->load->model('travel_agent_model');        
    } 

    /*
     * Listing of vendor_details
     */
   public function index()
    {
        
            
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 

        if($this->session->userdata('user_type')==1){
        $data['travel_agent'] = $this->travel_agent_model->get_all_agents();
        // var_dump($data['travel_agent']);die;
        $data['_view'] = 'travel_agent/index';
        $this->load->view('admin/index',$data);
        }
    }

    /*
     * Adding a new travelagent
     */
	function add()
    {   

        
        if(isset($_POST) && count($_POST) > 0)     
        {   

            
           
            extract($this->input->post());
            

                $loginparams= array(
                    'password' => md5($password),
                    'username' => $name, 
                    'phone_no' => $phone_no,
					'email' => $email,
                    'user_type' => 4,
                    'status' => 1,
					
                );
                
                $id = $this->Login_user_model->add_login_user($loginparams);
                
                $userparams= array(
                'login_id' => $id,
                'name' => $name,
                'phone_no' => $phone_no,
                'travelagent'=>1,
				'email' => $email,
                'address' => $address,
                'hotel_acc_no' => $hotel_acc_no,
                'hotel_ifsc_code' => $hotel_ifsc_code,
                'fullname' => $fullname,
                'acc_branch' => $acc_branch,
                'gst_no' => $gst_no,
                'pan_no' => $pan_no,
                );
 
                $user_detail_id = $this->User_detail_model->add_user_detail($userparams);
                $user_details = $this->User_detail_model->get_user_detail($user_detail_id);

                if($user_detail_id!=null){
                    // $otp = rand(100001, 999999);
                    $otp = 123456;
                  $loginp= array('otp' => $otp);
                 $up= $this->Login_user_model->update_login_user($id,$loginp);

                $res['userdetails'] = $user_details;

                // if($email!=null && $up !=null){
                //     $config = Array(
                //         'protocol' => 'smtp',
                //         'smtp_host' => 'ssl://smtp.gmail.com',
                //         'smtp_port' => 465,
                //         'smtp_user' => 'srikanth456789@gmail.com',
                //         'smtp_pass' => 'Sri@2017',
                //         'mailtype'  => 'html', 
                //         'charset'   => 'iso-8859-1'
                //     );
                //     $this->load->library('email');
                //     $this->email->initialize($config);
                //     $this->email->set_newline("\r\n");
                //     $this->email->from('srikanth456789@gmail.com', 'Your Name'); 
                //     $this->email->to($email);
                //     $this->email->subject('OTP for Login'); 
                //     $this->email->message('Please Enter the following otp for Login :'.$otp);
                    
                    
                //     $result = $this->email->send();
                // }

                }
                
				redirect('travel_agent/index');
                
        }
		else
        {     


            $data['_view'] = 'travel_agent/add';
            $this->load->view('admin/index',$data);
        }
 
       
    }  


    public function addvendor(){

    }

    /*
     * Editing a vendor_detail
     */
    function edit($id)
    {   
        // check if the vendor_detail exists before trying to edit it
        $data['agent_detail'] = $this->travel_agent_model->get_agent($id);
        
        if(isset($data['agent_detail']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   

                // adding new parameters to the below array to update the new fields into the table user_detils
                $params = array(
					
					'name' => $this->input->post('name'),
					'phone_no' => $this->input->post('phone_no'),
					'email' => $this->input->post('email'),
                    'address' => $this->input->post('address'),
                    'hotel_acc_no' => $this->input->post('hotel_acc_no'),
                    'hotel_ifsc_code' => $this->input->post('hotel_ifsc_code'),
                    'fullname' => $this->input->post('fullname'),
                    'acc_branch' => $this->input->post('acc_branch'),
                    'gst_no' => $this->input->post('gst_no'),
                    'pan_no' => $this->input->post('pan_no'),
                );
                $login_params = array(
                    
                    'username' => $this->input->post('name'),
                    'phone_no' => $this->input->post('phone_no'),
                    'email' => $this->input->post('email'),
                    
                   
                );

                $this->Login_user_model->update_login_user($id,$login_params);    
                $this->User_detail_model->update_user_detail($id,$params);        
                redirect('travel_agent/index');
            }
            else
            {
                $data['_view'] = 'travel_agent/edit';
                $this->load->view('admin/index',$data);
            }
        }
        else
            show_error('The Travel agent you are trying to edit does not exist.');
    } 

    /*
     * Deleting vendor_detail
     */
    function remove($id)
    {
        $vendor_detail = $this->Vendor_detail_model->get_vendor_detail($id);

        // check if the vendor_detail exists before trying to delete it
        if(isset($vendor_detail['id']))
        {
            $this->Vendor_detail_model->delete_vendor_detail($id);
            redirect('vendor_detail/index');
        }
        else
            show_error('The vendor_detail you are trying to delete does not exist.');
    }


    function dashboard(){
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        }    
        $data['_view'] = 'vendor_detail/dashboard';
        $this->load->view('admin/index', $data);
    }

    
    function amount_gained()
    {
    $id = $_SESSION['login_id'];
            
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 

        $data['amount_gained'] = $this->travel_agent_model->amount_gained($id);
        // $data['total']=$this->travel_agent_model->booked_number($id);
          // var_dump($data['travel_agent']);die;
        $data['_view'] = 'travel_agent/amount';
        $this->load->view('admin/index',$data);
        
    }
    
}
