<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_rating extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_rating_model');
    } 

    /*
     * Listing of user_ratings
     */
    function index()
    {
        $data['user_ratings'] = $this->User_rating_model->get_all_user_ratings();
        
        $data['_view'] = 'user_rating/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_rating
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'hotel_id' => $this->input->post('hotel_id'),
				'ratings' => $this->input->post('ratings'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
				'review' => $this->input->post('review'),
            );
            
            $user_rating_id = $this->User_rating_model->add_user_rating($params);
            redirect('user_rating/index');
        }
        else
        {            
            $data['_view'] = 'user_rating/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_rating
     */
    function edit($id)
    {   
        // check if the user_rating exists before trying to edit it
        $data['user_rating'] = $this->User_rating_model->get_user_rating($id);
        
        if(isset($data['user_rating']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'hotel_id' => $this->input->post('hotel_id'),
					'ratings' => $this->input->post('ratings'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'review' => $this->input->post('review'),
                );

                $this->User_rating_model->update_user_rating($id,$params);            
                redirect('user_rating/index');
            }
            else
            {
                $data['_view'] = 'user_rating/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_rating you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_rating
     */
    function remove($id)
    {
        $user_rating = $this->User_rating_model->get_user_rating($id);

        // check if the user_rating exists before trying to delete it
        if(isset($user_rating['id']))
        {
            $this->User_rating_model->delete_user_rating($id);
            redirect('user_rating/index');
        }
        else
            show_error('The user_rating you are trying to delete does not exist.');
    }
    
}
