<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_type extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_type_model');
    } 

    /*
     * Listing of user_types
     */
    function index()
    {
        $data['user_types'] = $this->User_type_model->get_all_user_types();
        
        $data['_view'] = 'user_type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_type
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
            );
            
            $user_type_id = $this->User_type_model->add_user_type($params);
            redirect('user_type/index');
        }
        else
        {            
            $data['_view'] = 'user_type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_type
     */
    function edit($id)
    {   
        // check if the user_type exists before trying to edit it
        $data['user_type'] = $this->User_type_model->get_user_type($id);
        
        if(isset($data['user_type']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
                );

                $this->User_type_model->update_user_type($id,$params);            
                redirect('user_type/index');
            }
            else
            {
                $data['_view'] = 'user_type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_type
     */
    function remove($id)
    {
        $user_type = $this->User_type_model->get_user_type($id);

        // check if the user_type exists before trying to delete it
        if(isset($user_type['id']))
        {
            $this->User_type_model->delete_user_type($id);
            redirect('user_type/index');
        }
        else
            show_error('The user_type you are trying to delete does not exist.');
    }
    
}
