<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vendor_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vendor_detail_model');
        $this->load->model('Login_user_model');        
    } 

    /*
     * Listing of vendor_details
     */
    function index()
    {

        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 

        if($this->session->userdata('user_type')==1){
        $data['vendor_details'] = $this->Vendor_detail_model->get_all_vendor_details();
        
        $data['_view'] = 'vendor_detail/index';
        $this->load->view('admin/index',$data);
        }
    }

    /*
     * Adding a new vendor_detail
     */
    function add()
    {  
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        } 

        
        if($this->session->userdata('user_type')==1){
            // var_dump("hello");die;
        if(isset($_POST) && count($_POST) > 0)     
        {                  
            extract($this->input->post());
            $loginparams= array(
                'password' => md5($password),
                'username' => $name,
                'email' => $email,
                'phone_no' => $phone_no,
                'user_type' => $user_type,
                'status' => 1,
            );
            $id = $this->Login_user_model->add_login_user($loginparams);
            $userparams= array(
            // 'business_name' => $business_name,
            'login_id' => $id,
            'name' => $name,
            'phone_no' => $phone_no,
            'email' => $email,
            'address' => $address,
            'hotel_acc_no' => $hotel_acc_no,
            'hotel_ifsc_code' => $hotel_ifsc_code,
            'full_name' => $full_name,
            'acc_branch' => $acc_branch,
            );
            // $vendor_detail_id = $this->Vendor_detail_model->add_vendor_detail($userparams);
            // $params = array(
			// 	'login_id' => $this->input->post('login_id'),
			// 	'name' => $this->input->post('name'),
			// 	'phone_no' => $this->input->post('phone_no'),
			// 	'email' => $this->input->post('email'),
			// 	'business_name' => $this->input->post('business_name'),
			// 	'created_at' => $this->input->post('created_at'),
			// 	'updated_at' => $this->input->post('updated_at'),
			// 	'address' => $this->input->post('address'),
            // );
            
            $vendor_detail_id = $this->Vendor_detail_model->add_vendor_detail($userparams);
            redirect('vendor_detail/index');
        }
        else
        {            
            $data['_view'] = 'vendor_detail/add';
            $this->load->view('admin/index',$data);
        }
    }
    }  


    public function addvendor(){

    }

    /*
     * Editing a vendor_detail
     */
    function edit($id)
    {   
        // check if the vendor_detail exists before trying to edit it
        $data['vendor_detail'] = $this->Vendor_detail_model->get_vendor_detail($id);
        
        if(isset($data['vendor_detail']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					
					'name' => $this->input->post('name'),
					'phone_no' => $this->input->post('phone_no'),
					'email' => $this->input->post('email'),
                    'address' => $this->input->post('address'),
                    'hotel_acc_no' => $this->input->post('hotel_acc_no'),
                    'hotel_ifsc_code' => $this->input->post('hotel_ifsc_code'),
                    'full_name' => $this->input->post('full_name'),
                    'acc_branch' => $this->input->post('acc_branch'),
                );
                $lid= $this->input->post('login_id');
                $login_params=array(
                   
                    'username' => $this->input->post('name'),
                    'phone_no' => $this->input->post('phone_no'),
                    'email' => $this->input->post('email'),
                    
                    
                    
                );
                $this->Login_user_model->update_login_user($lid,$login_params);

                $this->Vendor_detail_model->update_vendor_detail($id,$params);            
                redirect('vendor_detail/index');
            }
            else
            {
                $data['_view'] = 'vendor_detail/edit';
                $this->load->view('admin/index',$data);
            }
        }
        else
            show_error('The vendor_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting vendor_detail
     */
    function remove($id)
    {
        $vendor_detail = $this->Vendor_detail_model->get_vendor_detail($id);

        // check if the vendor_detail exists before trying to delete it
        if(isset($vendor_detail['id']))
        {
            $this->Vendor_detail_model->delete_vendor_detail($id);
            redirect('vendor_detail/index');
        }
        else
            show_error('The vendor_detail you are trying to delete does not exist.');
    }


    function dashboard(){
        if (!$this->session->userdata('is_logged_in')) {
            redirect('login_user/login');
        }    
        $data['_view'] = 'vendor_detail/dashboard';
        $this->load->view('admin/index', $data);
    }
    
}
