<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Room_model');
    } 

    /*
     * Listing of rooms
     */
    function index()
    {
        $data['rooms'] = $this->Room_model->get_all_rooms();
        
        $data['_view'] = 'room/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new room
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id' => $this->input->post('id'),
				'hotel_id' => $this->input->post('hotel_id'),
				'category_id' => $this->input->post('category_id'),
				'room_no' => $this->input->post('room_no'),
				'status' => $this->input->post('status'),
				'capacity' => $this->input->post('capacity'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
            );
            
            $room_id = $this->Room_model->add_room($params);
            redirect('room/index');
        }
        else
        {            
            $data['_view'] = 'room/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a room
     */
    function edit($id)
    {   
        // check if the room exists before trying to edit it
        $data['room'] = $this->Room_model->get_room($id);
        
        if(isset($data['room']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id' => $this->input->post('id'),
					'hotel_id' => $this->input->post('hotel_id'),
					'category_id' => $this->input->post('category_id'),
					'room_no' => $this->input->post('room_no'),
					'status' => $this->input->post('status'),
					'capacity' => $this->input->post('capacity'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
                );

                $this->Room_model->update_room($id,$params);            
                redirect('room/index');
            }
            else
            {
                $data['_view'] = 'room/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The room you are trying to edit does not exist.');
    } 

    /*
     * Deleting room
     */
    function remove($id)
    {
        $room = $this->Room_model->get_room($id);

        // check if the room exists before trying to delete it
        if(isset($room['']))
        {
            $this->Room_model->delete_room($id);
            redirect('room/index');
        }
        else
            show_error('The room you are trying to delete does not exist.');
    }
    
}
