<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Amenity_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get amenity by id
     */
    function get_amenity($id)
    {
        return $this->db->get_where('amenities',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all amenities
     */
    function get_all_amenities()
    {
        
        $this->db->order_by('id', 'desc');
        if($this->session->userdata('user_type')==1||$this->session->userdata('user_type')==2){
            $user_id=$this->session->userdata('login_id');
            $this->db->where('user_id',null)->or_where('user_id',$user_id);
        return $this->db->get('amenities')->result_array();
        }else{
        return $this->db->get('amenities')->result_array();
        }
    }
        
    function get_hotel_amenities()
    {
        $user_id=$this->session->userdata('login_id');
            $this->db->order_by('id', 'desc');
            $this->db->or_where('user_id',$user_id);
        return $this->db->get('amenities')->result_array();
        
    }
    /*
     * function to add new amenity
     */
    function add_amenity($params)
    {
        $this->db->insert('amenities',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update amenity
     */
    function update_amenity($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('amenities',$params);
    }
    
    /*
     * function to delete amenity
     */
    function delete_amenity($id)
    {
        return $this->db->delete('amenities',array('id'=>$id));
    }
}
