<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cancellation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cancellation by 
     */
    function get_cancellation($id)
    {
        return $this->db->get_where('cancellation_policies',array('hotel_id'=>$id))->row_array();
    }
        
    /*
     * Get all cancellation
     */
    function get_all_cancellation()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('cancellation')->result_array();
    }
        
    /*
     * function to add new cancellation
     */
    function add_cancellation($params)
    {
        $this->db->insert('cancellation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cancellation
     */
    function update_cancellation($id,$params)
    {
        $this->db->where('',$id);
        return $this->db->update('cancellation',$params);
    }
    
    /*
     * function to delete cancellation
     */
    function delete_cancellation($id)
    {
        return $this->db->delete('cancellation',array(''=>$id));
    }
}
