<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Payment_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get payment_detail by id
     */
    function get_payment_detail($id)
    {
        return $this->db->get_where('payment_details',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all payment_details
     */
    function get_all_payment_details()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('payment_details')->result_array();
    }
        
    /*
     * function to add new payment_detail
     */
    function add_payment_detail($params)
    {
        $this->db->insert('payment_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update payment_detail
     */
    function update_payment_detail($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('payment_details',$params);
    }
    
    /*
     * function to delete payment_detail
     */
    function delete_payment_detail($id)
    {
        return $this->db->delete('payment_details',array('id'=>$id));
    }
}
