<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reservation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hotel_model');
        $this->load->model('Room_category_model');
    }
    
    /*
     * Get reservation by id
     */
    function get_reservation($id)
    {
        return $this->db->get_where('reservations',array('id'=>$id))->row_array();
    }
    function get_rerservation_by_serach($params,$tid=NULL)
    {

        $from=$params['from'];
        $to=$params['to'];
        $category=$params['category'];
        $id=$params['booking_id'];
        $location=$params['location'];
        if($tid==NULL)
        {
        if($id=='')
        {
        if($from=='' && $to=='')
        {
        if($category=="all")
        {
            if($location != '')
            {
            $query=("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations , hotels ,room_categories WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id AND hotels.location='$location' ");
        }
        else
        {
             $query=("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations , hotels ,room_categories WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id ");

        }
        }
        else
        {
             if($location != '')
            {
             $query=("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations , hotels ,room_categories WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id AND booking_status='$category' AND hotels.location='$location' ");
         }
         else
         {
             $query=("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations , hotels ,room_categories WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id AND booking_status='$category' ");
         }
        }
    }
    else
    {
        if($category=="all")
        {
            if($location !='')
            {
       $query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations INNER JOIN hotels ON hotels.id=reservations.hotel_id INNER JOIN room_categories 
                ON room_categories.id=reservations.category_id WHERE hotels.location='$location' AND (
(cast(reservations.check_in as date) BETWEEN '$from' AND '$to')
 OR                           
(cast(reservations.check_out as date) BETWEEN '$from' AND '$to')) ");
   }
   else
   {
$query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations INNER JOIN hotels ON hotels.id=reservations.hotel_id INNER JOIN room_categories 
                ON room_categories.id=reservations.category_id WHERE  (
(cast(reservations.check_in as date) BETWEEN '$from' AND '$to')
 OR                           
(cast(reservations.check_out as date) BETWEEN '$from' AND '$to')) ");
   }
    }
   
   else
   {
    if($location !='')
            {
    $query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations INNER JOIN hotels ON hotels.id=reservations.hotel_id INNER JOIN room_categories 
                ON room_categories.id=reservations.category_id WHERE  booking_status='$category' AND hotels.location='$location' AND (
(cast(reservations.check_in as date) BETWEEN '$from' AND '$to')
 OR                           
(cast(reservations.check_out as date) BETWEEN '$from' AND '$to')) ");
}
else
{
     $query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations INNER JOIN hotels ON hotels.id=reservations.hotel_id INNER JOIN room_categories 
                ON room_categories.id=reservations.category_id WHERE  booking_status='$category' AND (
(cast(reservations.check_in as date) BETWEEN '$from' AND '$to')
 OR                           
(cast(reservations.check_out as date) BETWEEN '$from' AND '$to')) ");
}

}
}
}

else
{
    $query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations , hotels ,room_categories WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id AND reservations.id='$id' ");
}
}
else
{
    if($id=='')
        {
        if($from=='' && $to=='')
        {
        if($category=="all")
        {
            $query=("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations , hotels ,room_categories WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id    AND hotels.vendor_name='$tid' ");
        }
        else
        {
             $query=("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname  FROM 
              
                reservations , hotels ,room_categories WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id AND  hotels.vendor_name='$tid' AND booking_status='$category' ");
        }
    }
    else
    {
        if($category=="all")
        {
       $query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations INNER JOIN hotels ON hotels.id=reservations.hotel_id INNER JOIN room_categories 
                ON room_categories.id=reservations.category_id  WHERE  hotels.vendor_name='$tid' AND (
(cast(reservations.check_in as date) BETWEEN '$from' AND '$to')
 OR                           
(cast(reservations.check_out as date) BETWEEN '$from' AND '$to')) ");
    }
   
   else
   {
    $query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations INNER JOIN hotels ON hotels.id=reservations.hotel_id INNER JOIN room_categories 
                ON room_categories.id=reservations.category_id   WHERE  booking_status='$category' AND hotels.vendor_name='$tid' AND (
(cast(reservations.check_in as date) BETWEEN '$from' AND '$to')
 OR                           
(cast(reservations.check_out as date) BETWEEN '$from' AND '$to')) ");
}
}
}
else
{
    $query= ("SELECT reservations.*,hotels.hotel_name as name,room_categories.category_name as catname FROM 
              
                reservations , hotels ,room_categories,sub_category WHERE hotels.id=reservations.hotel_id
                AND room_categories.id=reservations.category_id AND  hotels.vendor_name='$tid' AND reservations.id='$id' ");
}
}


       return $this->db->query($query)->result_array();
}
   
        

           
    
        
    /*
     * Get all reservations
     */
    function get_all_reservations($id=NULL)
    {
        if($id==NULL)
        {
        $this->db->select('reservations.*,hotels.hotel_name as name,room_categories.category_name as catname')
                ->from('reservations')
                ->join('hotels','hotels.id=reservations.hotel_id')
                ->join('room_categories','room_categories.id=reservations.category_id')
                // ->join('sub_category','reservations.sub_category_id=sub_category.id')
        //         // ->join('payment_types','payment_types.id = revservations.payment_type')
              ->order_by('id', 'desc');
            // $this->db->query("SELECT r.*, h.hotel_name ,r.category_name,s.sub_name FROM reservations r, hotels h,")
            }
            else
            {
                   $this->db->select('reservations.*,hotels.hotel_name as name,room_categories.category_name as catname')
                ->from('reservations')
                ->join('hotels','hotels.id=reservations.hotel_id')
                ->join('room_categories','room_categories.id=reservations.category_id')
                // ->join('sub_category','reservations.sub_category_id=sub_category.id')
                ->where('hotels.vendor_name=',$id)
                // ->join('payment_types','payment_types.id = revservations.payment_type')
                ->order_by('id', 'desc');
            }
        return $this->db->get()->result_array();
    }
    // by agent reservations

            function reservations_by_agent()
    {
        $query = "select * ,room_categories.category_name as catname
            from reservations
            inner join user_details on user_details.login_id = reservations.user_id
            inner join  hotels on hotels.id=reservations.hotel_id
            inner join room_categories on room_categories.id=reservations.category_id

            where user_details.travelagent=1";
        return $this->db->query($query)->result_array();
    }
        
	
    /*
     * function to add new reservation
     */
    function add_reservation($params)
    {
        $this->db->insert('reservations',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reservation
     */
    function update_reservation($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('reservations',$params);
    }
    
    function get_pay_at_hotel($id){
        $this->db->where('hotel_id',$id);
        return $this->db->get('pay_at_hotel')->row_array();
    }
    /*
     * function to delete reservation
     */
    function delete_reservation($id)
    {
        return $this->db->delete('reservations',array('id'=>$id));
    }

  function get_avaliability_by_date($cat,$date){
        $query = "SELECT reservations.hotel_id,category_id,room_categories.no_of_rooms as rooms,sub_category_id,reservations.no_of_rooms as booked, room_categories.capacity as capacity from  room_categories 
        INNER JOIN reservations on reservations.category_id = room_categories.id
        where ('".$date."' BETWEEN cast(reservations.check_in as date) AND cast(reservations.check_out as date)) and category_id ='".$cat."'and booking_status = 'booked' 
        
        GROUP BY reservations.hotel_id";
        return $this->db->query($query)->row_array();
    }

    function get_avaliability_by_date_sub($scat,$date){
        $query = "SELECT reservations.hotel_id,reservations.category_id,sub_category_id,sub_category.num_of_rooms as rooms,reservations.no_of_rooms as booked,sub_category.capacity as capacity from  sub_category 
        INNER JOIN reservations on reservations.sub_category_id = sub_category.id
        where ('".$date."' BETWEEN cast(reservations.check_in as date) AND cast(reservations.check_out as date)) and sub_category_id ='".$scat."'and booking_status = 'booked' 
        
        GROUP BY reservations.hotel_id";
        return $this->db->query($query)->row_array();
    }

    function booked_hotel($params){
        $query = "SELECT hotels.hotel_name,hotels.hotel_grade,hotels.hotel_pic,hotels.hotel_address,reservations.check_in,reservations.check_out,room_categories.category_name,reservations.no_of_persons,reservations.no_of_rooms,reservations.total_price,
        hotels.amenities,room_categories.amenities as category_amenities,reservations.id,DATEDIFF(reservations.check_out, reservations.check_in) AS no_of_days
         from hotels 

        INNER JOIN
        room_categories 
        ON hotels.id = room_categories.hotel_id
        INNER JOIN 
        reservations
        ON room_categories.hotel_id = reservations.hotel_id
        WHERE
         hotels.id='".$params['hotel_id']."'  
        AND
        room_categories.id= '".$params['category_id']."'
        AND 
        reservations.id='".$params['booking_id']."'
        ";
        return $this->db->query($query)->result_array();
        
    }
        function booked_hotel2($data){
        $query = "SELECT hotels.hotel_name,hotels.hotel_grade,hotels.hotel_pic,hotels.hotel_address,reservations.check_in,reservations.check_out,room_categories.category_name,reservations.no_of_persons,reservations.no_of_rooms,reservations.total_price,reservations.guest_name,
        hotels.amenities,room_categories.amenities as category_amenities,reservations.id,DATEDIFF(reservations.check_out, reservations.check_in) AS no_of_days
         from hotels 

        INNER JOIN
        room_categories 
        ON hotels.id = room_categories.hotel_id
        INNER JOIN 
        reservations
        ON room_categories.hotel_id = reservations.hotel_id
        WHERE
         hotels.id='".$data['reservation']['hotel_id']."'  
        AND
        room_categories.id= '".$data['reservation']['hotel_id']."'
        AND 
        reservations.id='".$data['reservation']['id']."'
        ";
        return $this->db->query($query)->result_array();
        
    }

    
}
