<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get room_category by id
     */
    function get_room_category($id)
    {
        return $this->db->get_where('room_categories',array('id'=>$id))->row_array();
    }
    function get_room_catgory($id)
    {
        $sq="SELECT category_name as name,amenities,price,baseprice as base_price FROM room_categories where id='$id'";
        return $this->db->query($sq)->row_array();
    }

    function get_sub_room_category($id)
    {
        return $this->db->get_where('sub_category',array('id'=>$id))->row_array();
    }
        function update_sub_room($hotel_id,$category_id)
        {
            // $query="UPDATE `sub_category` SET `sub_name`='".$params['sub_name']." ' ,`num_of_rooms`='".$params['num_of_rooms']."',`capacity`='".$params['capacity']."' ,`amenities`='".$params['amenties']."',`base_price`='".$params['base_price']."',`price`='".$params['price']."',`updated_at`='".$params['updated_at']."' WHERE hotel_id='".$params['hotel_id']." ' AND category_id='".$params['category_id']."' AND created_at=(SELECT min' "
            $query="SELECT min(created_at) as min ,min(id) as id FROM sub_category WHERE hotel_id='$hotel_id' AND category_id='$category_id' ";
           return  $this->db->query($query)->row_array();
        }
    /*
     * Get all room_categories
     */
    function get_all_room_categories($id=NULL)
    {
        // $this->db->order_by('id', 'desc');
        // return $this->db->get('room_categories')->result_array();
        if($id==NULL)
        {
        $query="SELECT h.hotel_name,r.* FROM hotels h,room_categories r WHERE h.id=r.hotel_id ";
    }
    else
    {
         $query="SELECT h.hotel_name,r.* FROM hotels h,room_categories r WHERE h.id=r.hotel_id AND h.vendor_name='$id ' ";
    }
        return $this->db->query($query)->result_array();
    
    }
    function get_all_room_sub_categories($id=NULL)
    {
        if($id==NULL)
        {
			$query = "SELECT h.hotel_name,r.category_name,s.* FROM hotels h INNER JOIN room_categories r ON h.id=r.hotel_id INNER JOIN sub_category s ON " .
					"r.id=s.category_id  WHERE r.category_name <> s.sub_name";
        }
        else
        {
			$query = "SELECT h.hotel_name,r.category_name,s.* FROM hotels h INNER JOIN room_categories r ON h.id=r.hotel_id INNER JOIN sub_category s ON " .
					"r.id=s.category_id WHERE  r.category_name <> s.sub_name AND h.vendor_name='$id' ";
        }
        return $this->db->query($query)->result_array();
    }
     function get_all_room_categories_by_htl($id)
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get_where('room_categories',array('hotel_id'=>$id))->result_array();
    }
        
    /*
     * function to add new room_category
     */
    function add_room_category($params)
    {
        $this->db->insert('room_categories',$params);
        return $this->db->insert_id();
    }
    function add_sub_rooms($params)
    {
        $this->db->insert('sub_category',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update room_category
     */
    function update_room_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('room_categories',$params);
    }
    function update_sub_category($id,$params)
    {
        $this->db->where('id',$id);
       $result= $this->db->update('sub_category',$params);
    //    echo $this->db->last_query();
        return  $result;
        
    }
    function update_category_sub_category($min,$params)
    {

        $this->db->where('created_at',$min);
       $result= $this->db->update('sub_category',$params);
    //    echo $this->db->last_query();
        return  $result;
    }
    
    /*
     * function to delete room_category
     */
    function delete_room_category($id)
    {
        return $this->db->delete('room_categories',array('id'=>$id));
    }
    
    function delete_sub_category($id)
    {
        return $this->db->delete('sub_category',array('id'=>$id));
    }

    function get_room_categories_by_hotel_id($id){
        $this->db->where('hotel_id',$id);
        return $this->db->get('room_categories')->result_array();
    }
    
    function get_price($category_id){
    
        $query="SELECT price ,double_price,extra_bed_price from room_categories where id=$category_id ";
    return $this->db->query($query)->row_array();
    }
    
    function get_tax($hotel_id)
    {
       $sql= $this->db->query(" SELECT * from taxes WHERE hotel_id='$hotel_id'  ");
        return $sql->result_array();
    }
    
    function get_pics($id,$room)
    {
        
         $que="SELECT * FROM `gallery` where hotel_id ='".$id."' and category_id ='".$room."' and sub_category_id is null";
         return $this->db->query($que)->result_array();
    }

    function get_subcategories_by_category($id){
        $this->db->select('*');
        $this->db->from('sub_category');
        $this->db->where(['category_id'=>$id]);
        return $this->db->get()->result_array();
    }

    function get_subcategories_by_hotelid($id){
        $this->db->select('s.*, r.category_name');
        $this->db->from('sub_category as s');
        $this->db->join('room_categories as r', 'r.id = s.category_id');
        $this->db->where(['s.hotel_id'=>$id]);
        return $this->db->get()->result_array();
    }
    function get_hotel($id){
        $this->db->where('id',$id);
        return $this->db->get('room_categories')->row_array();
    }
    
   
}
