<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get room by 
     */
    function get_room($id)
    {
        return $this->db->get_where('rooms',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all rooms
     */
    function get_all_rooms()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('rooms')->result_array();
    }
        
    /*
     * function to add new room
     */
    function add_room($params)
    {
        $this->db->insert('rooms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update room
     */
    function update_room($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('rooms',$params);
    }
    
    /*
     * function to delete room
     */
    function delete_room($id)
    {
        return $this->db->delete('rooms',array('id'=>$id));
    }
}
