<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Taxes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get room by 
     */
    function get_taxes($id)
    {
        return $this->db->get_where('taxes',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all rooms
     */
    function get_all_taxes()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('taxes')->result_array();
    }
        
    /*
     * function to add new room
     */
    function add_tax($params)
    {
        $this->db->insert('taxes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update room
     */
    function update_taxes($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('taxes',$params);
    }
    
    /*
     * function to delete room
     */
    function delete_tax($id)
    {
        return $this->db->delete('taxes',array('id'=>$id));
    }

    function get_taxpercent($price)
    {
        return $this->db->get_where('taxes',array('min <='=>$price,'max >=' => $price))->row_array();
    }
}
