<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class travel_agent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_detail by id
     */
    function get_all_agents()
    {
        $this->db->select('*');
        $this->db->from('user_details');
        $this->db->join('login_users','login_users.id = user_details.login_id');
        $this->db->where('user_type','4');
        return $this->db->get()->result_array();
        // return $this->db->get_where('user_details')->result_array();
    }
function get_agent($id)
{
    //return $this->db->get_where('login_users',array('id'=>$id))->row_array();
    $this->db->select('*');
        $this->db->from('user_details');
        $this->db->join('login_users','login_users.id = user_details.login_id');
        // $this->db->where('user_type','4');
        $this->db->where('user_details.login_id',$id);
        return $this->db->get()->row_array();
}
    function amount_gained($id)
    {
        
         $query = "SELECT count(*) FROM reservations WHERE user_id = '$id'";
        return $this->db->query($query)->result_array();
    }
    //   function booked_number($id)
    // {
        
    //      $query = "SELECT count(*) FROM reservations WHERE user_id = '$id'";
    //     return $this->db->query($query)->result_array();
    // }
        
   
}
