<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_detail by id
     */
    function get_user_detail($id)
    {
        return $this->db->get_where('user_details',array('id'=>$id))->row_array();
    }

      /*
     * Get user_detail by login id
     */
    function get_user_detail_by_login_id($id)
    {
        return $this->db->get_where('user_details',array('login_id'=>$id))->row_array();
    }
        
    /*
     * Get all user_details
     */
    function get_all_user_details()
    {
        // $this->db->order_by('id', 'desc');
        // return $this->db->get('user_details')->result_array();
        $this->db->select('*');
        $this->db->from('user_details');
        $this->db->join('login_users','login_users.id = user_details.login_id');
        $this->db->where('user_type','3');
        $this->db->order_by('user_details.id', 'desc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new user_detail
     */
    function add_user_detail($params)
    {
        $this->db->insert('user_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_detail
     */
    function update_user_detail($id,$params)
    {   
       

         // $que="UPDATE user_details SET name='".$params['name']."' ,phone_no='".$params['phone_no']."',email='".$params['email']."'  WHERE login_id ='".$id."'";
         // return $this->db->query($que);

           $this->db->where('login_id',$id);
        return $this->db->update('user_details',$params);
      
            }



        function update_user_detail1($id,$params)
    {   
       

         $this->db->where('id',$id);
        return $this->db->update('login_users',$params);

        //    $this->db->where('id',$d);
        // return $this->db->update('login_users',$params);

    
    }
    
    /*
     * function to delete user_detail
     */
    function delete_user_detail($id)
    {
        return $this->db->delete('user_details',array('id'=>$id));
    }
}
