<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_type by id
     */
    function get_user_type($id)
    {
        return $this->db->get_where('user_types',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all user_types
     */
    function get_all_user_types()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('user_types')->result_array();
    }
        
    /*
     * function to add new user_type
     */
    function add_user_type($params)
    {
        $this->db->insert('user_types',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_type
     */
    function update_user_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('user_types',$params);
    }
    
    /*
     * function to delete user_type
     */
    function delete_user_type($id)
    {
        return $this->db->delete('user_types',array('id'=>$id));
    }
}
