<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vendor_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vendor_detail by id
     */
    function get_vendor_detail($id)
    {
        return $this->db->get_where('vendor_details',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all vendor_details
     */
    function get_all_vendor_details()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vendor_details')->result_array();
    }
        
    /*
     * function to add new vendor_detail
     */
    function add_vendor_detail($params)
    {
        $this->db->insert('vendor_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vendor_detail
     */
    function update_vendor_detail($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vendor_details',$params);
    }
    
    /*
     * function to delete vendor_detail
     */
    function delete_vendor_detail($id)
    {
        return $this->db->delete('vendor_details',array('id'=>$id));
    }
}
